global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules.yml

scrape_configs:
  - job_name: "monitor"
    static_configs:
      - targets: ["monitor:8000"]

  - job_name: "lanscan"
    scrape_interval: 60s
    static_configs:
      - targets: ["10.0.0.64:8001"]
